cnpm/mirrors

.gitignore
.jshintignore
.jshintrc
.npmignore
.travis.yml
LICENSE.txt
Makefile
README.md
app.js
config/index.js
dispatch.js
models/dist_file.js
package.json
sync/index.js
sync/iojs.js
sync/node.js
sync/syncer.js

feat(iojs): add iojs dist syncer

---

app.js
bin/nodejsctl
config/index.js
controllers/dist.js
controllers/home.js
models/index.js
package.json
routes.js
sync/index.js
views/dist.html
views/home.html

feat(config): support path start with /mirrors

---

sync/syncer.js

fix(sync): log upload size error

---

config/index.js
controllers/dist.js
sync/index.js
sync/npm.js
sync/phantomjs.js
sync/syncer.js

feat(npm): add npm syncer

---

controllers/apis/dist.js
routes.js
test/controllers/apis/dist.test.js

feat: add mirros api

---

config/index.js
controllers/dist.js
sync/index.js
sync/mirrors.js
views/dist.html

feat: sync from other mirrors

---

.travis.yml
config/index.js
models/init_script.js
services/dist.js
sync/chromedriver.js
sync/mirrors.js
sync/syncer.js
test/services/dist.test.js

feat(syncer): add chromedriver syncer

---

controllers/home.js
views/home.html

feat(home): add usage description

---

.travis.yml
app.js
package.json
sync/index.js

- use co@4
- use bluebird and fix memory v8 gc too lazy problem

Use bluebird instead of native Promise

---

controllers/dist.js

fix: real download as stream on nfs

---

config/index.js
sync/ListBucketResult.js

feat: support node-inspector

---

.travis.yml
config/index.js
sync/alinode.js
sync/index.js
views/home.html

feat: mirror alinode

---

config/index.js
sync/GithubWithVersion.js
sync/index.js

usage: SASS_BINARY_SITE=http://localhost:7001/node-sass cnpm install node-sass
closes #85

feat: mirror node-sass

---

sync/GithubWithVersion.js
sync/github.js

closes #87 cnpm/cnpmjs.org#746

fix: ignore file size >= 200mb files

---

config/index.js
sync/sqlite3.js
sync/syncer.js
views/home.html

feat: sync sqlite3

---

config/index.js

https://github.com/Level/leveldown/releases

feat: mirror leveldown

---

config/index.js
sync/node.js

feat: support sync node.js rc

---

config/index.js
sync/nodegit.js
sync/syncer.js
test/controllers/dist.test.js

feat: mirror nodegit

---

config/index.js

https://github.com/cnpm/cnpm/issues/117#issuecomment-222349077

feat: sync flow

---

config/index.js

feat: mirror poi

---

config/index.js
sync/node.js

closes https://github.com/cnpm/cnpmjs.org/issues/985

feat: sync nodejs nightly

---

config/index.js
sync/nw.js
test/controllers/apis/nodesecurity/advisories.test.js

closes https://github.com/cnpm/mirrors/issues/107

feat: mirror nwjs

---

config/index.js
sync/alinode.js
sync/nsolid.js

closes https://github.com/cnpm/mirrors/issues/110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/111)

feat: mirror nsolid

---

config/index.js

closes https://github.com/cnpm/mirrors/issues/112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/113)

feat: mirror git-for-windows

---

config/index.js
package.json
sync/SourceForge.js
sync/sourceforge_test.rss

closes https://github.com/cnpm/mirrors/issues/114

feat: mirror libjpeg-turbo

---

config/index.js
sync/python.js

https://github.com/cnpm/cnpmjs.org/issues/492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/118)

fix: enable python mirror again

---

config/index.js
sync/grpc.js
sync/sqlite3.js

closes https://github.com/cnpm/cnpm/issues/168
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/119)

feat: mirror grpc binary

---

config/index.js
sync/GithubWithVersion.js

close https://github.com/cnpm/mirrors/issues/123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/124)

feat: mirror node-chakracore

---

config/index.js
lib/utils.js
sync/nodegit.js
sync/sqlite3.js
sync/syncer.js

closes https://github.com/cnpm/mirrors/issues/99
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/127)

fix: add missing node abi versions

---

config/index.js

closes https://github.com/cnpm/cnpmjs.org/issues/1091
https://cnpmjs.org/mirrors/geckodriver/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/128)

feat: mirror geckodriver

---

app.js
common/logger.js
common/nfs.js
common/sequelize.js
config/index.js
dispatch.js
models/dist_dir.js
models/dist_file.js
models/index.js
models/init_script.js
sync/ListBucketResult.js
sync/atom-shell.js
sync/github.js
sync/index.js
sync/iojs.js
sync/mirrors.js
sync/phantomjs.js
worker.js

closes https://github.com/cnpm/cnpmjs.org/issues/1112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/132)

feat: mirror atom-shell

---

bin/nodejsctl
config/index.js
services/dist.js
sync/docker.js
sync/index.js
sync/syncer.js

closes https://github.com/cnpm/mirrors/issues/138
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/139)

feat: mirror docker

---

sync/atom-shell.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/142)

fix: wait for all files upload success before sync

---

views/home.html

* 更新home页视图，把usage提前，方便查看
* 更新 nvm 的设置说明
* 更新 electron-rebuild 的设置说明

refactor: update home page style, list usage at first page

---

config/index.js
sync/moby.js

https://github.com/moby/moby
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/150)

feat: rename docker to moby

---

views/home.html

`npm` and `yarn` version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/151)

add `node-inspector` mirror usage

---

config/index.js

closes https://github.com/cnpm/mirrors/issues/153
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/154)

feat: mirror yarn

---

config/index.js

close #131
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/156)

not remove prefix of version for git-for-windows

---

config/index.js

closes https://github.com/cnpm/mirrors/issues/162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/163)

feat: mirror utf-8-validate

---

config/index.js
package.json
sync/grpc.js
sync/sqlite3.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/167)

fix: grpc need to add glibc type

---

config/index.js
sync/PuppeteerChromeSyncer.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/168)

feat: mirror puppeteer chromium-browser-snapshots

---

config/index.js
sync/syncer.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/169)

feat: allow custom download url

---

config/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/174)

fix: set needFormatTagName=false on yarn mirror config

---

config/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/176)

fix: nwjs new disturl

---

sync/nodegit.js

see https://github.com/nodegit/nodegit/commit/9a653ab2de940171f7afe73d50b70d0aa19ca156
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/177)

fix: change nodegit binary download url

---

config/index.js
sync/cypress.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/182)

Mirror cypress

---

config/index.js
sync/jpegtran-bin.js

https://github.com/cnpm/mirrors/issues/183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/188)

feat: mirror jpegtran-bin

---

config/index.js
sync/jpegtran-bin.js
sync/pngquant-bin.js

https://github.com/cnpm/mirrors/issues/183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/189)

feat: mirror pngquant bin

---

config/index.js
sync/jpegtran-bin.js
sync/zopflipng-bin.js

https://github.com/cnpm/mirrors/issues/183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/190)

feat: mirror zopflipng bin

---

sync/grpc.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/197)

fix: sync from new url after grpc@1.14.0

---

config/index.js

close #200
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/201)

feat: mirror sentry-cli

---

sync/PuppeteerChromeSyncer.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/203)

fix: chrmoe file detect

---

config/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/206)

feat: mirror sharp-libvips

---

config/index.js

https://github.com/lovell/sharp/releases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/207)

feat: mirror sharp

---

sync/nw.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/211)

change the limit size of nw.js package to 200MB

---

app.js
config/index.js
test/controllers/apis/dist.test.js
test/controllers/dist.test.js
test/controllers/home.test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/217)

feat: sync tfjs-models

---

config/index.js

https://github.com/node-gfx/node-canvas-prebuilt/releases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/219)

feat: mirror node-canvas-prebuilt

---

views/home.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/223)

fix sqlite3 mirror usage

---

config/index.js
views/home.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/226)

feat: mirror electron-builder-binaries

---

config/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/232)

feat: support mirror node-swc binary

---

config/index.js
sync/ListBucketResult.js
sync/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/233)

Fix add random sync interval

---

common/logger.js
config/index.js
package.json
sync/index.js
sync/sqlcipher.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/236)

feat: support sync sqlcipher

---

Makefile
controllers/dist.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/239)

fix: auto fix /v or / not 'v' prefix

---

README.md
config/index.js
package.json
sync/github.js
sync/syncer.js

closes https://github.com/cnpm/cnpmjs.org/issues/1539
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/243)

feat: support electron-builder-binaries

---

sync/grpc.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/244)

feat: grpc support linux musl

---

sync/mirrors.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/246)

feat: use gzip request

---

config/index.js

https://github.com/X-Profiler/xprofiler/releases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/247)

feat: mirror xprofiler

---

sync/sqlite3.js

https://github.com/mapbox/node-sqlite3/blob/29debf3ad7d052427541503d871d6c69ed8588a7/package.json#L16
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/249)

feat: support napi on sqlite3 >= 5.0.0

---

config/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/250)

feat: mirror https://github.com/looksgood/s2/releases/

---

sync/PuppeteerChromeSyncer.js

https://unpkg.com/puppeteer@5.1.0/lib/cjs/revisions.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/252)

feat: support puppeteer >= 5.0.0

---

config/index.js

https://storage.googleapis.com/tensorflow/
https://github.com/tensorflow/tfjs/blob/master/tfjs-node/scripts/install.js#L45
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/253)

feat: mirror tensorflow files

---

config/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/255)

feat: mirror https://github.com/octalmage/robotjs

---

sync/PuppeteerChromeSyncer.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/259)

fix: chromium_revisions should be string

---

.gitignore
config/index.js
test/sync/canvas.test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/263)

feat: add canvas mirror config

---

.travis.yml
config/index.js

https://github.com/yanyiwu/nodejieba/releases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/mirrors/264)

feat: mirror nodejieba binary files

---

config/index.js
controllers/dist.js
sync/sqlcipher.js
sync/sqlite3.js

```log
node-pre-gyp http GET https://oss.npmmirror.com/dist/@journeyapps/sqlcipher/v5.3.1/napi-v6-darwin-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://oss.npmmirror.com/dist/@journeyapps/sqlcipher/v5.3.1/napi-v6-darwin-arm64.tar.gz 
```

🐛 FIX: sqlcipher rename to @journeyapps/sqlcipher

---

config/index.js

closes https://github.com/cnpm/cnpmjs.org/issues/1694

👌 IMPROVE: Use new electron mirror source
